# Generated by Django 5.2.5 on 2025-08-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.TextField()),
                ('medicines', models.TextField()),
            ],
            options={
                'verbose_name': 'Advice',
                'verbose_name_plural': 'Advices',
            },
        ),
    ]
